services:
  technical_test:
    container_name: technical_test
    build:
      context: ./Docker
      dockerfile: Dockerfile
    volumes:
      - ./srcs:/usr/src/app
    environment:
      DEBUG: ${DEBUG}
      EDITOR: vim
      TZ : "Europe/Paris"
    restart: always
    ports:
      - 8000:8000
